<?php
 /**
  * Language: French
  */

  /* Tableau de Bord */
  $lang['dashboard_welcome_to'] = utf8_encode('Bienvenue à ');
  $lang['dashboard_welcome_text'] = utf8_encode('gnsCMS a été construit pour être rapide, fiable et facile à naviguer tout en gardant à l\'esprit une simplicité globale qui le rend si merveilleux. Notre souhait est que tous ceux qui le souhaitent peuvent créer leur propre site web sans la nécessité de concepteurs de sites Web à prix élevé et de maintenir l\'apparence, la structure et l\'expérience utilisateur globale de leurs visiteurs tout sur leur propre . Nous espérons que vous apprécierez la fonctionnalité simple mais puissant ce système a à offrir.');
  $lang['dashboard_welcome_signature'] = '<em>-- Gerald Bullard Jr :: gnsPLANET</em>';
  $lang['dashboard_getting_started'] = 'Mise en Route';
  $lang['dashboard_getting_help'] = 'Obtenir de l\'aide';
  $lang['dashboard_highlights'] = utf8_encode('Voici quelques-uns des points forts du système de gestion de contenu gnsCMS &copy;. S\'il vous plaît prendre quelques instants pour regarder par-dessus les notes de la zone avant de commencer.');
  $lang['dashboard_draggable_sorting'] = 'Tri Draggable';
  $lang['dashboard_layout_templates'] = utf8_encode('Modèles de mise en Page');
  $lang['dashboard_multi_language'] = 'Multilingue';
  $lang['dashboard_sitemap'] = utf8_encode('Auto Génération Plan du Site');
  $lang['dashboard_description'] = utf8_encode('Vous êtes sur la page de tableau de bord maintenant. Cette page sera ensuite donné plus utiliser pour les stats, les membres, la messagerie et plus que le système gnsCMS pousse dans la portée.');
  $lang['dashboard_content_description'] = utf8_encode('La zone de contenu est l\'endroit où vous passerez la plupart de votre temps dans la création d\'admin et l\'édition de contenu (Catégories et Pages). Cette zone est l\'endroit où l\'essentiel de la mise en valeur des gnsCMS a été porté jusqu\'à ce point. Nous espérons que vous apprécierez sa puissance et sa simplicité!');
  $lang['dashboard_themes_description'] = utf8_encode('Une zone à contrôler votre site Theme (ou modèle) et les paramètres relatifs a été ajouté. Le principal objectif de ce domaine est d\'encourager le développement de tiers Thèmes et augmenter considérablement les choix de conception à votre disposition lors de la création ou de la mise à jour de votre site web.');
  $lang['dashboard_file_manager_description'] = utf8_encode('Un gestionnaire de fichiers est une nécessité évidente pour tout système de cms vrai. Nous avons suivi le rythme avec le choix fait par le développeur(s) du réactif Charisma Responsive Admin Template appelé elFinder. Sa simplicité et de puissance sont l\'une des caractéristiques remarquables de gnsCMS &copy;.');
  $lang['dashboard_settings_description'] = utf8_encode('La zone Paramètres a été ajouté pour aider à la zone de données sur l\'utilisation et les paramètres répétés à travers l\'extrémité d\'accueil du site. Cette zone permettra développeurs et créateurs de thème avec une table de base de données disponible pour maintenir les paramètres de configuration, les données au niveau du site (noms, coordonnées, adresses, titres, etc) et les paramètres "commutables" nécessaires dans le processus de création.');
  $lang['dashboard_search_description'] = utf8_encode('Un contenu Ajax Recherche a été ajouté à accélérer la localisation d\'un catégorie de votre choix ou la page pour l\'édition ou la création. Amusez-vous!');
  $lang['dashboard_draggable_description'] = utf8_encode('Dans chaque contenu Liste ligne, vous <img src="img/sortIcon.png"> verrez l\'icône de tri déplaçable du contenu par la catégorie endroit où vous résidez actuellement dans la page. Ceci est une autre caractéristique très remarquable et accélère le déploiement de n\'importe quel site web grandement.');
  $lang['dashboard_users_groups_description'] = utf8_encode('La possibilité d\'ajouter, modifier, activer, désactiver et supprimer des utilisateurs a été ajoutée. Également des groupes (Niveaux d\'accès) ont été ajoutées ainsi à soutenir la page action/accès spécifique tout au long de l\'administrateur par groupe d\'utilisateurs. Chaque utilisateur peut alors être affecté à un groupe spécifique qui permet l\'accès souhaité.');
  $lang['dashboard_layout_description'] = utf8_encode('Lors de l\'ajout d\'une nouvelle page, vous pouvez maintenant sélectionner stock mises en page si le fournisseur de Thème leur a fourni au bon endroit dans la structure de dossier du thème. Cette fonctionnalité permet d\'accélérer considérablement la mise en œuvre des dispositions de page standard pour le thème du site actif et enregistrer une grande quantité de travail html pour l\'utilisateur final.');
  $lang['dashboard_multi_lang_description'] = utf8_encode('La possibilité d\'ajouter plusieurs langues et sélectionner la langue de votre choix dans un menu déroulant en bas de page a été ajoutée. Improvments ultérieures comprendront les paramètres de langue spécifiques administrateur de l\'utilisateur, donnant à chaque administrateur la possibilité d\'enregistrer son prefernce pour qui la langue d\'administration actuel est en cours d\'utilisation lors de la session de l\'utilisateur. Il existe déjà un cookie de session qui est défini lors de la première connexion pour chaque utilisateur, sauver la langue de préférence pour 30 jours.');
  $lang['dashboard_sitemap_description'] = utf8_encode('Une caractéristique sitemap.xml de Génération Automatique a été ajoutée pour fournir les robots collecteurs sanitaires du moteur de recherche à jour xml sitemap à la demande avec aucune interaction de l\'administrateur du site. Cela entraîne aussi avec elle la réintroduction de la base de données colonne "publicationDate" et un ajouté pour "lastModified". La Fréquence de changement et de priorité ont également été ajoutés aux paramètres pour la modification facile à la valeur désirée.');
?>