<?php
 /**
  * Language: Español
  */

  /* Salpicadero */
  $lang['dashboard_welcome_to'] = 'Bienvenido a ';
  $lang['dashboard_welcome_text'] = utf8_encode('gnsCMS &copy; ha sido construido para ser rápido, fiable y fácil de navegar, mientras que teniendo en cuenta una simplicidad total que lo hace tan maravilloso. Nuestro deseo es que cualquier persona con el deseo puede crear su propio sitio web sin la necesidad de diseñadores de páginas web de alto precio y mantener la apariencia, la estructura y la experiencia general del usuario de sus visitantes todo por su cuenta. Esperamos que disfrute de la funcionalidad simple pero poderoso que este sistema tiene para ofrecer.');
  $lang['dashboard_welcome_signature'] = '<em>-- Gerald Bullard Jr :: gnsPLANET</em>';
  $lang['dashboard_getting_started'] = utf8_encode('Obtención de Ayuda');
  $lang['dashboard_getting_help'] = 'Primeros Pasos';
  $lang['dashboard_highlights'] = utf8_encode('A continuación se presentan algunos de los aspectos más destacados del Sistema de Gestión de Contenidos gnsCMS &copy;. Por favor, tómese unos minutos para mirar por encima de las obligaciones de la zona antes de comenzar.');
  $lang['dashboard_draggable_sorting'] = utf8_encode('Clasificación Arrastrable');
  $lang['dashboard_layout_templates'] = utf8_encode('Plantillas de Diseño');
  $lang['dashboard_multi_language'] = 'Multi Language';
  $lang['dashboard_sitemap'] = utf8_encode('Auto Generación Sitemap');
  $lang['dashboard_description'] = utf8_encode('Usted está en la página Dashboard ahora. Esta página será más tarde se dará un mayor uso de las estadísticas, los miembros, mensajería y más como el sistema gnsCMS &copy; crece en alcance.');
  $lang['dashboard_content_description'] = utf8_encode('El área de contenido es donde usted pasará la mayor parte de su tiempo, mientras que en la creación de administración y edición de contenido (Categorías y páginas). Esta zona es donde la mayor parte del desarrollo gnsCMS &copy; se ha centrado hasta este punto. Esperamos que disfrute de su poder y simplicidad!');
  $lang['dashboard_themes_description'] = utf8_encode('Un área de control de su sitio Web (o plantilla) y cualesquiera ajustes relacionados ha sido añadido. El objetivo principal de esta área es fomentar el desarrollo de temas de terceros y aumentar en gran medida las opciones de diseño a su disposición al crear o actualizar su sitio web.');
  $lang['dashboard_file_manager_description'] = utf8_encode('Un Administrador de archivos es una necesidad obvia de cualquier sistema cms verdad. Hemos ido a la par con la elección realizada por el promotor (s) de la planilla de administración Responsive Carisma llamado elFinder. Su simplicidad y la potencia son una de las características señaladas de gnsCMS &copy;');
  $lang['dashboard_settings_description'] = utf8_encode('El área de configuración se ha añadido para ayudar en el área de datos de uso repetido y la configuración a través de la parte frontal del sitio. Esta área le ayudará a desarrolladores y creadores de temáticas con una tabla de base de datos disponibles para mantener los valores de configuración, los datos a nivel de sitio (nombres, información de contacto, direcciones, títulos, etc) y los ajustes "conmutable" necesitan en el propio proceso de creación.');
  $lang['dashboard_search_description'] = utf8_encode('Un contenido Ajax Search se ha añadido para acelerar la localización de una categoría que desee o página para la edición o creación. Disfrute!');
  $lang['dashboard_draggable_description'] = utf8_encode('En cada fila Ficha Contenido que usted verá <img src="img/sortIcon.png"> el icono para la clasificación de los contenidos que pueden arrastrarse por la localización categoría que actualmente reside en la página. Esta es otra característica muy notable y en gran medida acelera el despliegue de cualquier sitio web.');
  $lang['dashboard_users_groups_description'] = utf8_encode('La capacidad de agregar, editar, activar, desactivar y eliminar usuarios ha sido añadido. También grupos (niveles de acceso) se ha añadido también a apoyar a la página/acción específico de acceso a lo largo del administrador por cada grupo de usuarios. Cada usuario puede ahora ser asignado a un grupo específico que permite el acceso deseado.');
  $lang['dashboard_layout_description'] = utf8_encode('Al añadir una nueva página, ahora se puede elegir entre los diseños de página de valores si el proveedor de Tema les ha suministrado en la ubicación correcta en la estructura de carpeta de temas. Esta característica se acelerará en gran medida la implementación de diseños de página estándar para el tema del sitio activo y guardar una gran cantidad de trabajo HTML para el usuario final.');
  $lang['dashboard_multi_lang_description'] = utf8_encode('La capacidad de agregar múltiples idiomas y seleccione el idioma de su elección de un menú desplegable en el pie de página se ha añadido. Alguna mejora posteriores incluirán ajustes de idioma específicos de usuarios administradores, dando a cada administrador la posibilidad de guardar su prefernce para que el lenguaje de administración actual está en uso durante la sesión de usuario. Ya existe una cookie de sesión que se establece en el primer inicio de sesión para cada usuario, el ahorro de la preferencia de la lengua durante 30 días.');
  $lang['dashboard_sitemap_description'] = utf8_encode('Una característica sitemap.xml de generación automática se ha añadido al proporcionar los robots de rastreo del motor de búsqueda con al día xml sitemap en la demanda, sin la interacción de la administración del sitio. Esto también trae consigo la reintroducción de la base de datos de la columna "PublicationDate" y un añadido de "lastModified". El cambio de frecuencia y prioridad también se han añadido a la configuración para una fácil modificación a su valor deseado.');
?>