<?php
 /**
  * Language: Deutsch
  */

  /* Armaturenbrett */
  $lang['dashboard_welcome_to'] = 'Willkommen auf ';
  $lang['dashboard_welcome_text'] = utf8_encode('<strong>gnsCMS</strong> &copy; wurde gebaut, schnell, zuverlässig und einfach zu navigieren sein, ohne dass dabei eine Gesamt Einfachheit, die sie so wunderbar macht. Unser Wunsch ist, dass jeder mit dem Wunsch, ihre eigene Website ohne die Notwendigkeit von teuren Web-Designer erstellen und das Aussehen, die Struktur und die allgemeine Benutzerfreundlichkeit ihrer Besucher alle auf ihre eigene zu halten. Wir hoffen, Sie genießen Sie die einfache, aber leistungsfähige Funktionalität dieses System zu bieten hat.');
  $lang['dashboard_welcome_signature'] = '<em>-- Gerald Bullard Jr :: gnsPLANET</em>';
  $lang['dashboard_getting_started'] = 'Erste Schritte';
  $lang['dashboard_getting_help'] = 'Erste Hilfe';
  $lang['dashboard_highlights'] = utf8_encode('Im Folgenden sind einige der Highlights der <strong>gnsCMS</strong> &copy; Content Management System. Bitte nehmen Sie sich ein paar Augenblicke über den Bereich Notizen zu suchen, bevor Sie beginnen.');
  $lang['dashboard_draggable_sorting'] = 'Draggable Sortierung';
  $lang['dashboard_layout_templates'] = 'Layoutvorlagen';
  $lang['dashboard_multi_language'] = 'Multi Language';
  $lang['dashboard_sitemap'] = 'Auto Sitemap Generieren';
  $lang['dashboard_description'] = utf8_encode('Sie sind auf der Dashboard-Seite jetzt. Diese Seite wird später mehr Einsatz für Statistik, Mitglieder, Messaging und mehr gegeben werden, da das System wächst <strong>gnsCMS</strong> &copy; Umfang.');
  $lang['dashboard_content_description'] = utf8_encode('Der Content Bereich ist, wo Sie die meiste Zeit, während in der Admin-Erstellung und Bearbeitung Gehalt (Kategorien und Seiten) verbringen. Dieser Bereich ist, wo der Großteil der <strong>gnsCMS</strong> &copy; Entwicklung bis zu diesem Punkt konzentriert. Wir hoffen, Sie genießen ihre Macht und Einfachheit!');
  $lang['dashboard_themes_description'] = utf8_encode('Ein Bereich, auf Ihre Website <strong>Theme</strong> (oder Vorlage) und alle zugehörigen Einstellungen steuern, wurde hinzugefügt. Der Schwerpunkt in diesem Bereich ist die Entwicklung von Dritten Themen fördern und die Design-Entscheidungen stark erhöhen zu Ihrer Verfügung, beim Erstellen oder Aktualisieren Ihrer Website.');
  $lang['dashboard_file_manager_description'] = utf8_encode('Ein <strong>Datei-Manager</strong> ist eine offensichtliche Notwendigkeit für jeden wahren CMS System. Wir haben Schritt mit der Wahl durch den Entwickler(s) des <strong>Charisma Responsive Admin Template</strong> namens <strong>elFinder</strong> gemacht gehalten. Seine Einfachheit und Leistung sind eine der bekanntesten Eigenschaften von <strong>gnsCMS</strong> &copy;.');
  $lang['dashboard_settings_description'] = utf8_encode('Der Bereich Einstellungen wurde hinzugefügt, um im Bereich der wiederholten Verwendung von Daten und Einstellungen über das Gelände vor Ende unterstützen. Dieser Bereich wird Entwickler und Themenerstellermit einer Datenbanktabelle verfügbar helfen, Konfigurationseinstellungen, Site-weite Daten (Namen, Kontaktinfo, Adressen, Titel etc.) und keine "schaltbare" Einstellungen in diesem Entstehungsprozess erforderlich halten.');
  $lang['dashboard_search_description'] = utf8_encode('Eine Ajax Inhalt Suche wurde hinzugefügt, um das Auffinden der gewünschten Kategorie oder Seite für die Bearbeitung oder Erstellung zu beschleunigen. Genießen Sie!');
  $lang['dashboard_draggable_description'] = utf8_encode('In jedem Inhalt Listing Zeile sehen Sie das Symbol für ziehbar Sortierung der Inhalte nach der Kategorie Ort, den Sie derzeit befinden sich in auf der Seite. Dies ist ein weiterer sehr bemerkenswertes Merkmal und beschleunigt die Bereitstellung von beliebigen Web-Site erheblich.');
  $lang['dashboard_users_groups_description'] = utf8_encode('Die Fähigkeit, hinzufügen, bearbeiten, aktivieren, deaktivieren und löschen Benutzer wurde hinzugefügt. Auch Gruppen (Zugriffsebenen) wurde hinzugefügt, sowie zu Seite/Action spezifischen Zugang in der Admin pro Benutzergruppe zu unterstützen. Jeder Benutzer kann nun auf eine spezifische Gruppe, die den gewünschten Zugriff erlaubt zugeordnet werden.');
  $lang['dashboard_layout_description'] = utf8_encode('Wenn Sie eine neue Seite, können Sie jetzt ab Lager Seitenlayouts wählen, wenn das Theme Anbieter hat sie in der richtigen Stelle in der Ordnerstruktur Thema geliefert. Diese Funktion wird die Umsetzung von Standard-Seitenlayouts für das aktive Zentrum Thema stark zu beschleunigen und speichern eine große Menge an html Arbeit für den Endverbraucher.');
  $lang['dashboard_multi_lang_description'] = utf8_encode('Die Fähigkeit, mehrere Sprachen hinzufügen, und wählen Sie die Sprache Ihrer Wahl aus einem Dropdown in der Fußzeile wurde hinzugefügt. Später wird improvments Admin-Benutzer spezifische Einstellungen gehören Sprache, so dass jeder Administrator die Möglichkeit, seine Vorliebe, für die aktuelle Admin-Sprache ist im Einsatz während der Benutzersitzung zu speichern. Es gibt bereits eine Cookie-Sitzung, bei der ersten Anmeldung für jeden Benutzer eingestellt ist, spart die bevorzugte Sprache für 30 Tage.');
  $lang['dashboard_sitemap_description'] = utf8_encode('Eine automatische Erzeugen sitemap.xml Funktion wurde hinzugefügt, um Suchmaschinen-Crawl-Bots mit aktuellen XML-Sitemap auf Nachfrage ohne Interaktion des Website-Administrator werden. Dies bringt auch die Wiedereinführung der Datenbankspalte "Publication" und einen Mehr ein für "lastModified". Die Frequenzänderungund Priorität haben auch die Einstellungen für einfache Änderungen an Ihrem gewünschten Wert hinzugefügt.');
?>